name: Déploiement sur Azure VM - Développement

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Connexion SSH et déploiement
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd ~ 
            cd coabi/api/dev
            git pull origin dev
            docker compose down || true
            docker compose up --build -d
